name: shared-ci-quality-check

on:
  workflow_call:

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Basic CI Check
        run: echo "Running Shared CI Quality Check"
